services:
  postgres:
    image: postgres:16-alpine
    container_name: agc-postgres
    environment:
      POSTGRES_DB: agcdb
      POSTGRES_USER: agc
      POSTGRES_PASSWORD: agcpassword
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./backend/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - agc-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U agc -d agcdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: agc-backend
    env_file: .env
    environment:
      DATABASE_URL: postgresql://agc:agcpassword@postgres:5432/agcdb
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - agc-net
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: agc-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - agc-net
    restart: unless-stopped

  simulator:
    build: ./simulator
    container_name: agc-simulator
    environment:
      MQTT_BROKER: a19bbaf9d8a74507a6d0a3ce8d4ddbad.s1.eu.hivemq.cloud
      MQTT_PORT: "8883"
      MQTT_USERNAME: GolfCart123
      MQTT_PASSWORD: IOTgc1234
    depends_on:
      - backend
    networks:
      - agc-net
    restart: unless-stopped

volumes:
  postgres-data:

networks:
  agc-net:
    driver: bridge
